package com.metacube.senchacon.demoapp.common.enums;

public enum FilterType
{
	INFORMANCE_USER_FILTER, INFORMANCE_REASON_FILTER, INFORMANCE_SET_FILTER, INFORMANCE_PART_FILTER,
	INFINITY_QS_USER_FILTER, INFINITY_QS_TEST_FILTER, INFINITY_QS_PART_FILTER, INFINITY_QS_QPM_FILTER, INFINITY_QS_PROCESS_FILTER
}
